Clear Data

In [6]:
import pandas as pd
import numpy as np


import matplotlib as plt

import seaborn as sns

In [7]:
df = pd.read_csv("raw/data.csv")

In [8]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 251079 entries, 0 to 251078
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Unnamed: 0                251079 non-null  int64
 1   brand                     251079 non-null  str
 2   model                     251079 non-null  str
 3   color                     250913 non-null  str
 4   registration_date         251075 non-null  str
 5   year                      251079 non-null  str
 6   price_in_euro             251079 non-null  str
 7   power_kw                  250945 non-null  str
 8   power_ps                  250950 non-null  str
 9   transmission_type         251079 non-null  str
 10  fuel_type                 251079 non-null  str
 11  fuel_consumption_l_100km  224206 non-null  str
 12  fuel_consumption_g_km     251079 non-null  str
 13  mileage_in_km             250927 non-null  float64
 14  offer_description         251078 non-null  str
dtypes: float64(1), int64(1), str(13)
memory usage: 28.7 MB
None
Unnamed: 0                      0
brand                           0
model                           0
color                         166
registration_date               4
year                            0
price_in_euro                   0
power_kw                      134
power_ps                      129
transmission_type               0
fuel_type                       0
fuel_consumption_l_100km    26873
fuel_consumption_g_km           0
mileage_in_km                 152
offer_description               1
dtype: int64

In [9]:
df.describe()

          Unnamed: 0  mileage_in_km
count  251079.000000   2.509270e+05
mean   125539.000000   8.534002e+04
std     72480.408456   7.871706e+04
min         0.000000   0.000000e+00
25%     62769.500000   2.490400e+04
50%    125539.000000   6.750000e+04
75%    188308.500000   1.265000e+05
max    251078.000000   3.800000e+06

In [21]:
df.drop(columns=["Unnamed: 0", "offer_description"], inplace=True)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 251079 entries, 0 to 251078
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   brand                     251079 non-null  str
 1   model                     251079 non-null  str
 2   color                     250913 non-null  str
 3   registration_date         251075 non-null  str
 4   year                      251079 non-null  str
 5   price_in_euro             251079 non-null  str
 6   power_kw                  250945 non-null  str
 7   power_ps                  250950 non-null  str
 8   transmission_type         251079 non-null  str
 9   fuel_type                 251079 non-null  str
 10  fuel_consumption_l_100km  224206 non-null  str
 11  fuel_consumption_g_km     251079 non-null  str
 12  mileage_in_km             250927 non-null  float64
dtypes: float64(1), str(12)
memory usage: 24.9 MB

In [23]:
print("Datensatzgröße:", df.shape)

df.head()

Datensatzgröße: (251079, 13)

,brand,model,color,registration_date,year,price_in_euro,power_kw,power_ps,transmission_type,fuel_type,fuel_consumption_l_100km,fuel_consumption_g_km,mileage_in_km
0,alfa-romeo,Alfa Romeo GTV,red,10/1995,1995,1300,148,201,Manual,Petrol,"10,9 l/100 km",260 g/km,160500.0
1,alfa-romeo,Alfa Romeo 164,black,02/1995,1995,24900,191,260,Manual,Petrol,NaN,- (g/km),190000.0
2,alfa-romeo,Alfa Romeo Spider,black,02/1995,1995,5900,110,150,Unknown,Petrol,NaN,- (g/km),129000.0
3,alfa-romeo,Alfa Romeo Spider,black,07/1995,1995,4900,110,150,Manual,Petrol,"9,5 l/100 km",225 g/km,189500.0
4,alfa-romeo,Alfa Romeo 164,red,11/1996,1996,17950,132,179,Manual,Petrol,"7,2 l/100 km",- (g/km),96127.0

In [24]:
# Проверяем содержимое столбцов
columns = ["year", "price_in_euro", "power_kw", "power_ps"]

for col in columns:
    # приводим к строке и убираем пробелы
    values = df[col].astype(str).str.strip()

    # оставляем только значения, которые НЕ являются числами
    invalid = values[
        (~values.str.fullmatch(r"\d+")) &
        (values != "nan") &
        (values != "None")
    ]

    print(f"\n{col}")
    print(f"Некорректных значений: {len(invalid)}")

    if len(invalid):
        print(invalid.unique()[:20])   # первые 20 различных значений

year
Некорректных значений: 195
<StringArray>
[    'Petrol',  'Automatic',     'Manual',     'Diesel',    '04/2017',
   'Electric',    '12/2003',    '05/2017',    '04/2006',        'LPG',
   '8.000 km', '113.000 km',  '32.250 km',    '02/2020',    '06/2021',
    '07/2021',     'Hybrid',    '03/2023',    '01/2019',    '10/2010']
Length: 20, dtype: str

price_in_euro
Некорректных значений: 199
<StringArray>
[         'KLIMAAUTOMATIK*',                'Automatik',
                   '6-Gang', 'XEN AAC SHZ FSP APS 5TRG',
   'NAVplus LEDER PANO ALC',                      'amp',
                   'Matrix',               'Navigation',
                'UPE  103',                    'Klima',
                    'LEDER',                 'ROSTFREI',
                 'ROSTHREI',                    'leder',
              'Remus Sport',               'Unfallfrei',
         '258 PS TÜV 07/24',    'NAVpro HUD HiFi AHK..',
    'Inkl-2.Jahre Garantie',      'AC-Schnitzer 360 PS']
Length: 20, dtype: str

power_kw
Некорректных значений: 293
<StringArray>
[           nan, '7,8 l/100 km', '5,4 l/100 km', '4,6 l/100 km',
     '121 g/km',     '129 g/km',   '7 l/100 km',     '- (g/km)',
      '03/2006', '7,5 l/100 km', '4,9 l/100 km', '5,3 l/100 km',
 '6,8 l/100 km', '8,3 l/100 km', '5,8 l/100 km',     '123 g/km',
     '152 g/km', '5,9 l/100 km', '5,6 l/100 km',     'Electric']
Length: 20, dtype: str

power_ps
Некорректных значений: 210
<StringArray>
[           nan,     '194 g/km',     '126 g/km', '4,6 l/100 km',
 '4,9 l/100 km',   '7 l/100 km',     '158 g/km',       'Petrol',
     '- (g/km)',     '153 g/km', '5,3 l/100 km',   '6 l/100 km',
     '117 g/km', '4,3 l/100 km', '1,2 l/100 km', '7,8 l/100 km',
     '170 g/km', '5,9 l/100 km', '5,5 l/100 km',     '122 g/km']
Length: 20, dtype: str

Удалить все строки, где числовые поля имеют неверный формат

In [25]:
import pandas as pd

mask = (
    df["year"].astype(str).str.fullmatch(r"\d{4}") &
    df["price_in_euro"].astype(str).str.fullmatch(r"\d+") &
    (
        df["power_kw"].isna() |
        df["power_kw"].astype(str).str.fullmatch(r"\d+")
    ) &
    (
        df["power_ps"].isna() |
        df["power_ps"].astype(str).str.fullmatch(r"\d+")
    )
)

print(f"Удаляется строк: {(~mask).sum()}")

df = df.loc[mask].copy()

Удаляется строк: 199

Преобразовать столбцы в числовой тип

In [26]:
numeric_cols = [
    "year",
    "price_in_euro",
    "power_kw",
    "power_ps"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [27]:
df.info()

<class 'pandas.DataFrame'>
Index: 250880 entries, 0 to 251078
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   brand                     250880 non-null  str
 1   model                     250880 non-null  str
 2   color                     250714 non-null  str
 3   registration_date         250880 non-null  str
 4   year                      250880 non-null  int64
 5   price_in_euro             250880 non-null  int64
 6   power_kw                  250752 non-null  float64
 7   power_ps                  250752 non-null  float64
 8   transmission_type         250880 non-null  str
 9   fuel_type                 250880 non-null  str
 10  fuel_consumption_l_100km  224007 non-null  str
 11  fuel_consumption_g_km     250880 non-null  str
 12  mileage_in_km             250818 non-null  float64
dtypes: float64(3), int64(2), str(8)
memory usage: 26.8 MB

In [28]:
for col in numeric_cols:
    print(col, df[col].isna().sum())

year 0
price_in_euro 0
power_kw 128
power_ps 128

In [29]:
duplicates = df.duplicated().sum()

print(
    f"Duplicate rows: {duplicates}"
)

Duplicate rows: 7096

In [38]:
duplicates = df[df.duplicated(keep=False)]

duplicates.sort_values(["brand", "model"]).head(20)

,brand,model,color,registration_date,year,price_in_euro,power_kw,power_ps,transmission_type,fuel_type,fuel_consumption_l_100km,fuel_consumption_g_km,mileage_in_km
106,alfa-romeo,Alfa Romeo 147,silver,10/2003,2003,1550,88.0,120.0,Manual,Petrol,"8,2 l/100 km",- (g/km),197000.0
107,alfa-romeo,Alfa Romeo 147,silver,10/2003,2003,1550,88.0,120.0,Manual,Petrol,"8,2 l/100 km",- (g/km),197000.0
173,alfa-romeo,Alfa Romeo 159,grey,09/2006,2006,3800,147.0,200.0,Automatic,Diesel,"8,1 l/100 km",215 g/km,210000.0
174,alfa-romeo,Alfa Romeo 159,grey,09/2006,2006,3800,147.0,200.0,Automatic,Diesel,"8,1 l/100 km",215 g/km,210000.0
562,alfa-romeo,Alfa Romeo Giulia,black,10/2016,2016,21890,132.0,179.0,Automatic,Diesel,"4,2 l/100 km",109 g/km,59900.0
566,alfa-romeo,Alfa Romeo Giulia,black,10/2016,2016,21890,132.0,179.0,Automatic,Diesel,"4,2 l/100 km",109 g/km,59900.0
1016,alfa-romeo,Alfa Romeo Giulia,blue,11/2022,2022,59990,206.0,280.0,Automatic,Petrol,"8,1 l/100 km",184 g/km,10.0
1018,alfa-romeo,Alfa Romeo Giulia,blue,11/2022,2022,59990,206.0,280.0,Automatic,Petrol,"8,1 l/100 km",184 g/km,10.0
1037,alfa-romeo,Alfa Romeo Giulia,grey,01/2022,2022,57900,206.0,280.0,Automatic,Petrol,"7,3 l/100 km",167 g/km,8500.0
1085,alfa-romeo,Alfa Romeo Giulia,grey,01/2022,2022,57900,206.0,280.0,Automatic,Petrol,"7,3 l/100 km",167 g/km,8500.0
1421,alfa-romeo,Alfa Romeo Giulia,black,02/2023,2023,47400,147.0,200.0,Automatic,Petrol,"7,1 l/100 km",164 g/km,5.0
1423,alfa-romeo,Alfa Romeo Giulia,black,02/2023,2023,47400,147.0,200.0,Automatic,Petrol,"7,1 l/100 km",164 g/km,5.0
956,alfa-romeo,Alfa Romeo Stelvio,red,12/2021,2021,57490,206.0,280.0,Automatic,Petrol,"7,4 l/100 km",170 g/km,50.0
957,alfa-romeo,Alfa Romeo Stelvio,red,12/2021,2021,57490,206.0,280.0,Automatic,Petrol,"7,4 l/100 km",170 g/km,50.0
1131,alfa-romeo,Alfa Romeo Stelvio,red,04/2022,2022,53990,206.0,280.0,Automatic,Petrol,"7,1 l/100 km",161 g/km,10.0
1132,alfa-romeo,Alfa Romeo Stelvio,red,04/2022,2022,53990,206.0,280.0,Automatic,Petrol,"7,1 l/100 km",161 g/km,10.0
1152,alfa-romeo,Alfa Romeo Stelvio,red,12/2022,2022,48990,154.0,209.0,Automatic,Diesel,"5,7 l/100 km",149 g/km,10.0
1153,alfa-romeo,Alfa Romeo Stelvio,red,12/2022,2022,48990,154.0,209.0,Automatic,Diesel,"5,7 l/100 km",149 g/km,10.0
1154,alfa-romeo,Alfa Romeo Stelvio,red,12/2022,2022,48990,154.0,209.0,Automatic,Diesel,"5,7 l/100 km",149 g/km,10.0
1155,alfa-romeo,Alfa Romeo Stelvio,red,12/2022,2022,48990,154.0,209.0,Automatic,Diesel,"5,7 l/100 km",149 g/km,10.0

In [40]:
print("До:", len(df))

df_no_duplicates = df.drop_duplicates()

print("После:", len(df_no_duplicates))
print("Удалено:", len(df) - len(df_no_duplicates))

До: 243784
После: 243784
Удалено: 0

In [39]:
df = df.drop_duplicates(keep="first").reset_index(drop=True)

In [43]:
df.to_csv("cleaned_cars.csv", index=False)

исследовательский анализ данных (EDA)

In [12]:
# Находим строки, где year не состоит только из цифр
mask = ~df["year"].astype(str).str.strip().str.fullmatch(r"\d+")

wrong_rows = df.loc[mask]

print(f"Количество строк: {len(wrong_rows)}")
wrong_rows.head()

Количество строк: 195

,Unnamed: 0,brand,model,color,registration_date,year,price_in_euro,power_kw,power_ps,transmission_type,fuel_type,fuel_consumption_l_100km,fuel_consumption_g_km,mileage_in_km,offer_description
2400,2400,audi,Audi A4,grey,Manual,Petrol,KLIMAAUTOMATIK*,"7,8 l/100 km",75,Manual,07/2004,187 g/km,2004,2460.0,Avant 1.6 *TÜV 09/23
2743,2743,audi,Audi A4,silver,8449,Automatic,Automatik,2005,194 g/km,Automatic,74.194 km,Petrol,11/2005,NaN,Lim. 2.0
5297,5297,audi,Audi A1,blue,8999,Manual,6-Gang,2011,126 g/km,Manual,110.250 km,Petrol,04/2011,NaN,1.4 TFSI Ambition
9616,9616,audi,Audi A1,white,Manual,Petrol,XEN AAC SHZ FSP APS 5TRG,"5,4 l/100 km",90,Manual,06/2014,128 g/km,2014,12250.0,Sportback Sportline
12206,12206,audi,Audi A6,black,Manual,Diesel,NAVplus LEDER PANO ALC,"4,6 l/100 km",140,Manual,12/2016,119 g/km,2016,21250.0,Avant 2.0 TDI ultra

In [30]:
duplicates = df.duplicated().sum()

print(
    f"Duplicate rows: {duplicates}"
)

Duplicate rows: 7096

2. data auditing

In [14]:
df = pd.read_csv("raw/data.csv")

In [15]:
def column_report(df):
    report = {}

    for col in df.columns:
        s = df[col].astype(str).str.strip()

        report[col] = {
            "unique_values_sample": s.value_counts().head(10),
            "nan_count": df[col].isna().sum(),
        }

    return report

report = column_report(df)

In [16]:
import pandas as pd

def find_non_numeric(df, col):
    s = df[col].astype(str).str.strip()

    # оставляем только строки, которые НЕ являются числом
    bad = s[~s.str.match(r"^-?\d+([.,]\d+)?$")]

    return bad.value_counts()

In [17]:
numeric_candidates = [
    "year",
    "price_in_euro",
    "power_kw",
    "power_ps",
    "fuel_consumption_l_100km",
    "fuel_consumption_g_km",
    "mileage_in_km"
]

for col in numeric_candidates:
    print("\n", col)
    print(find_non_numeric(df, col).head(20))

 year
year
Petrol       51
Hybrid       24
Manual       20
Diesel       20
Automatic    14
03/2023       5
12/2022       3
04/2017       2
02/2020       2
06/2021       2
07/2021       2
03/2015       2
05/2023       2
11/2018       2
Electric      1
12/2003       1
05/2017       1
04/2006       1
LPG           1
8.000 km      1
Name: count, dtype: int64

 price_in_euro
price_in_euro
DAB                 19
LED                  8
Navi                 8
AHK                  5
Kamera               4
ACC                  4
Klima                3
ROSTFREI             3
Standhzg.            3
FSE                  3
PDC                  3
Navigation           2
LEDER                2
TÜV NEU              2
wenig KM*            2
KLIMAAUT/AHK/GJR     2
wenig KM             2
SHA                  2
2.Hd                 2
7-Gang DSG           2
Name: count, dtype: int64

 power_kw
power_kw
2,8 l/100 km    13
Petrol          10
5,9 l/100 km     6
Diesel           6
6,8 l/100 km     5
4,9 l/100 km     4
3,8 l/100 km     4
5,4 l/100 km     3
129 g/km         3
7,5 l/100 km     3
5,8 l/100 km     3
4,5 l/100 km     3
6 l/100 km       3
5 l/100 km       3
86 g/km          3
4,6 l/100 km     2
121 g/km         2
7 l/100 km       2
- (g/km)         2
5,3 l/100 km     2
Name: count, dtype: int64

 power_ps
power_ps
4,9 l/100 km    4
3,8 l/100 km    4
158 g/km        3
5 l/100 km      3
7,9 l/100 km    3
5,4 l/100 km    3
Petrol          2
5,3 l/100 km    2
4,3 l/100 km    2
5,9 l/100 km    2
122 g/km        2
159 g/km        2
5,2 l/100 km    2
4,4 l/100 km    2
98 g/km         2
194 g/km        1
126 g/km        1
4,6 l/100 km    1
7 l/100 km      1
- (g/km)        1
Name: count, dtype: int64

 fuel_consumption_l_100km
fuel_consumption_l_100km
4,9 l/100 km    8158
5,1 l/100 km    7655
5,5 l/100 km    7614
5,9 l/100 km    7516
5,3 l/100 km    7435
5 l/100 km      6986
5,7 l/100 km    6447
5,4 l/100 km    6406
5,2 l/100 km    6309
5,8 l/100 km    6283
5,6 l/100 km    6206
4,5 l/100 km    5975
4,7 l/100 km    5946
4,8 l/100 km    5936
6 l/100 km      5731
6,1 l/100 km    5274
6,4 l/100 km    5179
6,2 l/100 km    4754
4,6 l/100 km    4565
6,3 l/100 km    4485
Name: count, dtype: int64

 fuel_consumption_g_km
fuel_consumption_g_km
- (g/km)    35809
0 g/km       8533
119 g/km     4813
114 g/km     3882
139 g/km     3389
130 g/km     3368
109 g/km     3356
129 g/km     3348
149 g/km     3338
125 g/km     3214
128 g/km     2915
135 g/km     2904
123 g/km     2765
140 g/km     2740
124 g/km     2714
134 g/km     2702
120 g/km     2623
116 g/km     2617
138 g/km     2594
127 g/km     2591
Name: count, dtype: int64

 mileage_in_km
Series([], Name: count, dtype: int64)

In [18]:
def detect_shifted_rows(df):
    mask = pd.Series(False, index=df.index)

    for col in df.columns:
        s = df[col].astype(str)

        # если в числовой колонке встречается буква → подозрительно
        mask |= s.str.contains(r"[A-Za-zÄÖÜäöü]", na=False)

    return df[mask]

bad_rows = detect_shifted_rows(df)

print(len(bad_rows))

251079

In [19]:
checks = {
    "year": r"^\d{4}$",
    "price_in_euro": r"^\d+$",
    "power_kw": r"^\d+(\.\d+)?$",
    "power_ps": r"^\d+(\.\d+)?$",
    "mileage_in_km": r"^\d+(\.\d+)?$"
}

for col, pattern in checks.items():
    bad = df[~df[col].astype(str).str.match(pattern, na=False)]
    print(col, "bad rows:", len(bad))

year bad rows: 198
price_in_euro bad rows: 199
power_kw bad rows: 293
power_ps bad rows: 210
mileage_in_km bad rows: 152

In [20]:
summary = pd.DataFrame({
    "missing": df.isna().sum(),
    "dtype": df.dtypes
})

summary

                          missing    dtype
Unnamed: 0                      0    int64
brand                           0      str
model                           0      str
color                         166      str
registration_date               4      str
year                            0      str
price_in_euro                   0      str
power_kw                      134      str
power_ps                      129      str
transmission_type               0      str
fuel_type                       0      str
fuel_consumption_l_100km    26873      str
fuel_consumption_g_km           0      str
mileage_in_km                 152  float64
offer_description               1      str